name: Deploy TopASS to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build_and_deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          # You can specify exact version if needed

      - name: Install dependencies
        working-directory: ./tass
        run: flutter pub get

      - name: Build Web
        working-directory: ./tass
        # The base-href must match your repository name exactly (including the slashes)
        run: flutter build web --release --base-href "/topass/"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './tass/build/web'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
